# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04

  tools:
    python: "3.13"

  commands:
    - pip install -U pip
    - pip install .
    - pip install --group docs
    - python -m sphinx -c docs docs/source $READTHEDOCS_OUTPUT/html/
